import { JWT } from "google-auth-library";
import { GoogleSpreadsheet } from "google-spreadsheet";
import "dotenv/config";

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const auth = new JWT({
    // env var values here are copied from service
    // account credentials generated by google
    // see "Authentication" section in docs for more info
    email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    key: process.env.GOOGLE_PRIVATE_KEY,
    scopes: [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive.file",
    ],
});

export const makeSpreadsheet = async () => {
    const newDoc = await GoogleSpreadsheet.createNewSpreadsheetDocument(auth, {
        title: "Sushi Squad Attendance",
    });
    if (process.env.GOOGLE_SPREADSHEET_SHARE_EMAIL) {
        await newDoc.share(process.env.GOOGLE_SPREADSHEET_SHARE_EMAIL);
        console.log("Shared with", process.env.GOOGLE_SPREADSHEET_SHARE_EMAIL);
    } else {
        await newDoc.share("sushisquad.org");
        await newDoc.share("redmondstemcenter.org");
        console.log("Shared with sushisquad.org and redmondstemcenter.org");
    }
    console.log(
        `\nNew spreadsheet created at https://docs.google.com/spreadsheets/d/${newDoc.spreadsheetId}`
    );
    console.log(`
Please update GOOGLE_ATTENDANCE_SHEET_ID in .env with the new spreadsheet ID.
    
    ${newDoc.spreadsheetId}

Copy and paste the above value.
    `);
    return newDoc;
};

export const makeSheet = async (sheetId: string, title: string) => {
    const doc = new GoogleSpreadsheet(sheetId, auth);
    await doc.loadInfo();
    const newSheet = await doc.addSheet({ title });
    console.log(
        `New sheet created at https://docs.google.com/spreadsheets/d/${sheetId}/edit#gid=${newSheet.sheetId}`
    );
};

export const deleteSheet = async (sheetId: string) => {
    const doc = new GoogleSpreadsheet(sheetId, auth);
    await doc.delete();
    console.log(
        `Deleted spreadsheet at https://docs.google.com/spreadsheets/d/${sheetId}`
    );
};

// Uncomment this to make a new attendance spreadsheet
makeSpreadsheet().then(async (doc) => {
    const sheet = await doc.addSheet({ title: "Attendance" });
    console.log(
        `Please add the following to your .env file:\n\n\tGOOGLE_ATTENDANCE_AGGREGATE_SHEET_ID=${sheet.sheetId}`
    );
    console.log("The headers should be [Email, Name, Hours, Attendance]");
});

// Uncomment this if you already have the spreadsheet
// const doc = new GoogleSpreadsheet(
//     process.env.GOOGLE_ATTENDANCE_SHEET_ID ?? "",
//     auth
// );
// doc.loadInfo().then(async () => {
//     const sheet = await doc.addSheet({ title: "Attendance" });
//     console.log(
//         `Please add the following to your .env file:\n\n\tGOOGLE_ATTENDANCE_AGGREGATE_WORKSHEET_ID=${sheet.sheetId}`
//     );
// });

// Uncomment this to delete the attendance spreadsheet
// deleteSheet(process.env.GOOGLE_ATTENDANCE_SHEET_ID);
