# workflow for building and deploying a svelte site to GitHub Pages
name: Build and Deploy to GitHub Pages with SvelteKit Static Adapter

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Install Dependencies & Build
        run:  cd pages && yarn install && yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./pages/dist

  # Deployment job
  deploy_gh_pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_gh_pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  build_and_deploy_functions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies and setup environment variables
      run: |
        cd firebase/functions
        yarn install
        echo "
        NOTION_TOKEN=${{secrets.NOTION_TOKEN}}
        NOTION_BOT_USER_ID=${{secrets.NOTION_BOT_USER_ID}}
        NOTION_ATTENDANCE_DBID=${{secrets.NOTION_ATTENDANCE_DBID}}
        NOTION_MEETINGS_DBID=${{secrets.NOTION_MEETINGS_DBID}}
        GOOGLE_ATTENDANCE_SHEET_ID=${{secrets.GOOGLE_ATTENDANCE_SHEET_ID}}
        GOOGLE_ATTENDANCE_AGGREGATE_WORKSHEET_ID=${{secrets.GOOGLE_ATTENDANCE_AGGREGATE_WORKSHEET_ID}}
        GOOGLE_SERVICE_ACCOUNT_EMAIL=${{secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL}}
        GOOGLE_PRIVATE_KEY=${{secrets.GOOGLE_PRIVATE_KEY}}" >> .env
    # Deploying the functions to firebase
    - name:  Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
          args: deploy --only functions
      env:
        GCP_SA_KEY: '${{ secrets.GCP_SA_KEY }}'
        PROJECT_PATH: './firebase'
